### ISSUE TITLE
查询float类型的数据与实际的数据不一致

### ISSUE THREAD

**Issue by tizxm** [xormplus/xorm#104]
![image](https://user-images.githubusercontent.com/22961290/127986177-6a8494b2-9fc1-4aaa-aa0c-357b04b0d8bc.png)
![image](https://user-images.githubusercontent.com/22961290/127986243-34f5db00-7f58-4ce4-b99a-ff08851dee35.png)
我使用SQL语句进行查询的时候，查询float类型的数据与数据实际的数据不一致，字段在数据库是float类型，查询到一个map类型的时候，数据不一致

**Comment by CyJaySong** [comment]
要高精度的话，用decimal

**Comment by tizxm** [comment]
> 要高精度的话，用decimal

数据库结构改动不了呀，数据量也比较多了，这个字段并不涉及计算，并且使用xorm查询过，xorm查询是正常的，使用结构体的时候也是正常的，当把数据使用map返回时才会出现数据错误
