### ISSUE TITLE
关于批量SQL操作

### ISSUE THREAD

**Issue by iamsee** [xormplus/xorm#14]
如以下代码
```

type AAA struct {
	ID   int    `xorm:"pk autoincr" json:"id"`
	Name string `xorm:"varchar(100)" json:"name"`
}
当 sql可以 为 []string 类型

paramsOld := make(map[string]interface{})
paramsOld["id"] = 1
paramsNew := make(map[string]interface{})
paramsNew["id"] = 2
paramsNew["name"] = "李四"
var paramsTotal []map[string]interface{}

paramsTotal = append(paramsTotal,paramsOld)
paramsTotal = append(paramsTotal,paramsNew)
engine.AddSql("insert1","insert into aaa (id,name) values (?id , ?name)")
engine.AddSql("insert2","insert into aaa (id , name) values (?id , ?name)")
sqlKey := []string{"insert1","insert2"}
sqlsExecutor := engine.SqlMapsClient(sqlKey, paramsTotal)
fmt.Println("sqlsExecutor",sqlsExecutor)
a,b,c := sqlsExecutor.Execute()

fmt.Println(a,b,c)
```
时候循环到第二次后
![image](https://user-images.githubusercontent.com/6944557/35719260-8f44d5a0-0823-11e8-8172-34523d4b738e.png)
isSqlFunc为 false 无法执行commit 会defer 自动回滚

当 sql可以 为 string 类型
判断case里面没有提交commit 。defer也会回滚无法提交

请问如何在代码里进行批量sql后commit

**Comment by iamsee** [comment]
使用的是第一种方式
![image](https://user-images.githubusercontent.com/6944557/35720250-c90af18a-0827-11e8-8874-ff2bd00cbfcf.png)

**Comment by xormplus** [comment]
恩，是个BUG，事务模型重构后，对批量sql操作有影响，感谢提交issue，这个问题会尽快修复

**Comment by iamsee** [comment]
@xormplus  是的目前使用的手动

**Comment by xormplus** [comment]
[fix bugs on Sqls，SqlMapsClient，SqlTemplatesClient](https://github.com/xormplus/xorm/commit/c3b43ecb4bab83c01bb40bfca5793cc9978359f1)
