### ISSUE TITLE
on DUPLICATE KEY update 会忽略掉

### ISSUE THREAD

**Issue by yale8848** [xormplus/xorm#16]
mysql.sql:

``` insert into xxx () values () on DUPLICATE KEY update ```

执行engine.SqlTemplateClient("mysql.sql").Insert(&b)后on之后的sql语句会忽略掉

engine.SQL("").Execute()可以执行

**Comment by xormplus** [comment]
目前是不支持engine.SqlTemplateClient().Insert()的调用模式的
Sql，SqlMapClient，SqlTemplateClient方法之后主要支持的是Query和Execute()方法

**Comment by yale8848** [comment]
请问有改善的计划吗？
SqlMapClient 不支持模板，SqlTemplateClient又不完善，实在不行又得直接在代码里写sql字串了

**Comment by xormplus** [comment]
SqlTemplateClient 是哪方面不完善？你的问题我还没有完全领会。
能否说下你的使用场景。

**Comment by yale8848** [comment]
哦 我说的不完善就是我提的这个问题，在重新构造sql的时候能否对原sql语句不破坏？

**Comment by xormplus** [comment]
你使用的engine.SqlTemplateClient().Insert()这种连调方式是错误的使用方式。
SqlTemplateClient("mysql.sql")中要传2个参数，第一个参数是sql模板的key，第二个参数是模板参数（可选），然后调用Execute()方法来执行insert、update或delete语句，这是RAW方式。
如果你后面紧跟Insert()方法，将会变成ORM方式，会重新构造sql语句，而不会执行sql模板。
目前SqlMap支持3种格式，xml、json、xsql。SqlMap初衷是配置静态sql。SqlTemplate是解决动态sql。
两者结合？你能否给一个样例，或伪代码，我还没理解你所说的结合是什么意思。

**Comment by yale8848** [comment]
好的，看来是我用法有问题了，谢谢指正；
我有SqlMap和SqlTemplate结合的想法的原因是：我测试RegisterSqlTemplate注册时不能注册子目录的模板文件，每条sql只能一个文件，这样感觉比较麻烦，就想着SqlMap和SqlTemplate结合，一个sqlmap文件可以写较多sql模板语句，如：
```
<sqlMap>
	<sql id="selectAllArticle">
		select id,userid,title,createdatetime,content 
               from Article where  
              {% if count>1%}
                  id=?id
              {% else%}
                  userid=?userid
             {% endif %}
	</sql>
</sqlMap>
```

**Comment by xormplus** [comment]
恩，你设想的这种方式最早我是有考虑过的，其实就是先读取sqlmap，然后每个key的配置内容执行sqltemplate。不过当时我想保留模板的include等功能，就将静态sql配置和动态sql两个功能分开了，这个方式目前来看还是可以再次考虑一下。我考虑下增加一个SqlTemplateMap功能，同时还要考虑下和原有功能兼容。

另外，RegisterSqlTemplate注册时候，会自动扫描配置目录下的所有子目录的sql模板，并读取到内存。你描述中的“RegisterSqlTemplate注册时不能注册子目录的模板文件”是什么样的情况？

**Comment by yale8848** [comment]
好的，谢谢及时回复！
RegisterSqlTemplate注册的问题我再测试测试
