### ISSUE TITLE
主键UUID

### ISSUE THREAD

**Issue by henjue** [xormplus/xorm#18]
主键怎么配置成UUID方式。没找到相关文档

**Comment by xormplus** [comment]
请看这个例子

[https://github.com/xormplus/xorm/blob/5a177643184ea98add48119552208888080a2f4c/session_pk_test.go#L1114](https://github.com/xormplus/xorm/blob/5a177643184ea98add48119552208888080a2f4c/session_pk_test.go#L1114)

**Comment by henjue** [comment]
@xormplus 我在tag里加了UUID。然而还是无效。难道是因为我字段名字不允许使用"id"？？

**Comment by xormplus** [comment]
你是什么数据库？对应数据库在数据库中设置对应的默认值
然后在tag中使用`<-`标记该字段为只读字段
就可以使用了
类似这样 
```
UID  string `xorm:"<- notnull pk UUID 'uid'"`
```

**Comment by henjue** [comment]
我突然意识到，我可能没有表达清楚我的问题。我是mysql，我需要一个像mybatisplus 那样的自动创建主键，自动生成UUID字符串当ID，而不是我自己去给pk 的列赋值。我的问题就是这个自动UUID无效。

**Comment by xormplus** [comment]
一个小例子，postgresql的
数据库建表sql
```
CREATE TABLE public.test (
	uid uuid NOT NULL DEFAULT uuid_generate_v4(),
	"name" varchar(100) NOT NULL
)
```
go简单代码
```
package main

import (
	"fmt"

	"github.com/xormplus/xorm"

	_ "github.com/lib/pq"
)

type Test struct {
	UID  string `xorm:"<- notnull pk UUID 'uid'"`
	Name string
}

var db *xorm.Engine

func main() {
	var err error
	db, err = xorm.NewPostgreSQL("postgres://postgres:root@localhost:5432/mblog?sslmode=disable")

	if err != nil {
		fmt.Println(err)
	}
	db.ShowSQL(true)

	_, err = db.Insert(Test{Name: "你好"})
	if err != nil {
		fmt.Println(err)
	}

	r, err := db.SQL("select * from test").QueryResult().List()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(r[0]["uid"].String())
}
```

**Comment by henjue** [comment]
@xormplus 数据库没有设置默认值得情况下，框架会自动生成UUID的主键不?

**Comment by xormplus** [comment]
不会的

**Comment by henjue** [comment]
好吧，那似乎这个声明称UUID并没有太大作用了。感觉和varchar(32)一样了

**Comment by xormplus** [comment]
不同数据库对uuid的实现和支持程度不同（包括golang的数据库驱动包），mssql中有UniqueIdentifier类型，在golang的mssql驱动包有UniqueIdentifier类型
[https://github.com/denisenkom/go-mssqldb/blob/master/uniqueidentifier.go#L10:6](https://github.com/denisenkom/go-mssqldb/blob/master/uniqueidentifier.go#L10:6)

而有些数据库uuid确实感觉和varchar(32)一样

**Comment by miniboom360** [comment]
现在支持mysql创建record的时候自动生成uuid了么，如果支持了，应该怎么做
