### ISSUE TITLE
SetSqlMapRootDir相关问题

### ISSUE THREAD

**Issue by piaohailin** [xormplus/xorm#2]
1、允许多个配置文件在RootDir文件夹中吗？A.xml;B,xml 多个文件都能加载吗？
2、不支持sql空间命名的方式吧？
3、我理解 xml json 不支持动态sql 是不是这个意思？
4、stpl 格式的模板可以实现动态sql，不过官方例子太简单了 没有sql id=模式？

**Comment by xormplus** [comment]
1、允许多个配置文件在RootDir文件夹中，A.xml;B,xml 多个文件都能加载。同时可以在RootDir文件夹中建立子目录，在不同子目录中的所有xml或json配置文件都会被加载。
2、每条配置的sql，在xml中的id要全局唯一，在json中的key要全局唯一，xml中的id和json中的key也不能重复，否则后加载的sql配置会覆盖之前加载的相同key。
3、动态sql需要使用sqltemplate功能，由于sql模板可以使用模板引擎的全部功能，则xml和json中只做简单sql配置。这一点和mybatis通过xml的OGNL方式实现动态sql不同。其实使用模板和写动态脚本类似的方式来写动态sql。
4、stpl 格式的模板可以实现动态sql，官方给出的是一个简单例子，同时把整个解析过程有一个详细讲解。参见[http://www.kancloud.cn/xormplus/xorm/235732](http://www.kancloud.cn/xormplus/xorm/235732)
其实我们可以用模板来渲染html页面或实现动态JavaScript，同样也可以使用模板来实现动态sql。xml和json就是用来配置静态sql的，而模板是用来实现动态sql。

疑问：@piaohailin 你最后那句“没有sql id=模式”没看明白，能都详细说明一下。

**Comment by piaohailin** [comment]
非常感谢！xml和json方式不可能有脚本语法的方式，只是做静态sql传入通配符参数。

**关于stpl。官方给例子给我的感觉是一个文件中只有一个动态sql，
    不能在一个stpl文件中有多个动态sql吗？，用id区分**不然会有多个stpl文件的没法管理。

**Comment by xormplus** [comment]
是的，不能在一个stpl文件中有多个动态sql。但是可以在一个stpl文件中使用pongo2的语法include其他模板。一个模板只配置一个动态sql，是这样的管理方式。

**Comment by xormplus** [comment]
[http://www.kancloud.cn/xormplus/xorm/167080](http://www.kancloud.cn/xormplus/xorm/167080)
这章节的 db.InitSqlTemplate()过程中有SqlTemplate的详细说明
