### ISSUE TITLE
sql查询问题

### ISSUE THREAD

**Issue by xhochipe** [xormplus/xorm#20]
错误码提示:
  SELECT a.id,a.title,a.content,a.created,c.name as c_name,c.id as cid,t.name as t_name,t.id as tid FROM `article` AS `a` INNER JOIN `article_tag` AS `at` ON at.aid = a.id INNER JOIN `tag` AS `t` ON at.tid = t.id INNER JOIN `article_category` AS `ac` ON a.id = ac.aid INNER JOIN `category` AS `c` ON ac.cid = c.id WHERE ( t.id = ?   and  a.is_valid = ) LIMIT 10 []interface {}{22222, 1}
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') LIMIT 10' at line 1 0

![image](https://user-images.githubusercontent.com/9391575/48056528-f2646f80-e1ec-11e8-8258-d46f6a214b2a.png)

我把sql复制出来查询
![image](https://user-images.githubusercontent.com/9391575/48056569-027c4f00-e1ed-11e8-81cd-6d2e87784177.png)

我不清楚这个报错是那块的，数据库版本是8.0 xormplus最最新拉取的

**Comment by xormplus** [comment]
我没有你的运行环境，但是看你提供的信息，好像是你sql语句构建的有问题。
你的错误提示中的代码是
`SELECT a.id,a.title,a.content,a.created,c.name as c_name,c.id as cid,t.name as t_name,t.id as tid FROM article AS a INNER JOIN article_tag AS at ON at.aid = a.id INNER JOIN tag AS t ON at.tid = t.id INNER JOIN article_category AS ac ON a.id = ac.aid INNER JOIN category AS c ON ac.cid = c.id WHERE ( t.id = ? and a.is_valid = ) LIMIT 10`
你最后这个where里有问题，`and a.is_valid = `是不是少了一个?号

而你在其他数据库客户端工具中执行的sql是有完整的where语句的`and a.is_valid = 1`
你看下你的golang代码中的query变量是不是有问题

**Comment by xhochipe** [comment]
@xormplus thanks
