### ISSUE TITLE
对于.stpl的sql模板问题

### ISSUE THREAD

**Issue by chuntaojun** [xormplus/xorm#21]
一个.stql文件是不是只能写一句sql？我看示例是一个文件里面就一sql语句

**Comment by xormplus** [comment]
是的。一个.stql文件对应一个sql片段，但是可以使用模板引擎自身功能引入其他模板。这里更提倡使用目录结构和模板的标准命名来组织sql模板文件。而不是放在都通通放在xml之类的格式文件里。其实放在xml格式的文件里也就是先解析xml在解析对应的内容交给模板引擎执行。

**Comment by chuntaojun** [comment]
嗯，好的
