### ISSUE TITLE
动态查询咨询

### ISSUE THREAD

**Issue by magic007** [xormplus/xorm#22]
很喜欢这种方式，可是如果我想表名称也通过变量传入进来，支持吗？
sql_i_3 := "insert.example.stpl"
paramMap_i_t := map[string]interface{}{"key": "config_3", "value": "3"}
affected, err := engine.SqlTemplateClient(sql_i_3, &paramMap_i_t).Execute()

**Comment by xormplus** [comment]
支持的，因为是先执行模板引擎然后交给xorm引擎。你可以动态的决定要执行的表名，字段，条件，以及他们的组合和子查询。可以理解为先执行HTML模板引擎然后在提交给浏览器。但是要注意的是，给模板引擎执行的部分不要造成给SQL引擎的执行内容已经被注入。模板里的占位符是同时可以被模板引擎或者xorm引擎执行的。有时候你编写的sql模板中的占位符可能只被模板引擎执行，也可能先被模板引擎执行后又被xorm引擎执行（因为map中的某个key可能先后被模板中引用作为条件判断，后又被xorm执行，因为是某个条件的值），这两种情况，你要注意防止sql注入。如果是只被xorm引擎使用的占位符，则不会被sql注入，因为本身是防注入的。
