### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by cloudfreexiao** [xormplus/xorm#23]
golang 版本
`go version go1.11.2 darwin/amd64`

错误日志如下
`go: finding github.com/xormplus/builder latest
go: finding github.com/agrison/go-tablib latest
go: finding github.com/Chronokeeper/anyxml latest
go: finding gopkg.in/flosch/pongo2.v3 latest
go: github.com/xormplus/builder@v0.0.0-20181205170700-0185e89d0c1a: parsing go.mod: unexpected module path "github.com/go-xorm/builder"
go: error loading module requirements`

**Comment by xormplus** [comment]
???我用的版本是go version go1.11 windows/amd64，我刚才全新go get -v github.com/xormplus/xorm 没有问题
我刚才把golang版本升级到最新版本go version go1.11.4 windows/amd64，我把gopath下的xormplus相关包全删除了，重新全新go get -v github.com/xormplus/xorm 也是好的啊

你shixia删除gopath下的xormplus相关包重新go get看看
