### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by iGoogle-ink** [xormplus/xorm#24]
作者，我看过你的文档说明后，看不出xormplus 在对比xorm上做出的具体功能添加和xormplus的优势点，能不能在文档里明确做一个功能对比呢，让用户更清晰的看出来，xormplus比xorm功能更强大的地方，谢谢

**Comment by xormplus** [comment]
好的，有时间的话我输出一下，不过以前很多功能已经合入xorm了（例如数据库读写分离等功能），只有一些需要依赖于第三方库的功能没有两边提交。目前xormplus有而xorm没有的功能主要是sqlmap、sqltemplate（动态sql）支持，复杂事务模型（支持嵌套事务，8种事务传播机制），支持sql查询直接导出csv、tsv、xml、json、xlsx、yaml、html功能，支持数据库查询结果直接返回Json字符串和xml字符串，更好的query查询支持，更好的limit功能支持等。其实你只要对比下kancloud上两个库的操作指南目录就很清楚差异了。

xorm的操作指南链接[https://www.kancloud.cn/kancloud/xorm-manual-zh-cn/56013](https://www.kancloud.cn/kancloud/xorm-manual-zh-cn/56013)

xormplus的操作指南链接[https://www.kancloud.cn/xormplus/xorm/167077](https://www.kancloud.cn/xormplus/xorm/167077)

于我而言，我们的实际项目对操作纯sql的需求更多一些，对事务相关的需求更多一些，所以我提交了很多与sql操作相关的功能。我们对orm的需求偏低，而且很多时候可以使用sqlbuilder来代替orm的操作需求。如果你只是需要使用orm功能或简单的纯sql操作，其实xorm已经足够满足需求了。xormplus并没有比xorm功能更强大（内核还是xorm的core），只是需求场景的偏重不同，但是xormplus又保留了援用xorm的所有功能，这也为项目中对一些表的简单操作保留了orm的操作方式。xormplus不像sqlx那种纯sql操作的库，也不像gorm那种重orm的库，这只是一个相对比较折中的库，所有功能都是依据实际项目需求慢慢新增的功能，比如数据库读写分离，动态sql，复杂事务模型等等。

**Comment by Linvas** [comment]
其实为什么不和xorm作者合作一起维护? xorm的中国开发者Lunny Xiao在很多群都可以找到他身影, 一起合作维护, 其实你还是认可xorm才做二次开发的, 和他们一起维护不就更好?

**Comment by CHCP** [comment]
@Linvas @xormplus 估计xorm的作者在功能上也有自己的考虑，但也赞成能把这两个ORM合并维护，对于用户来说使用一个ORM要比使用两个ORM选择简单。
