### ISSUE TITLE
Can I use xorm-redis-cache in xormplus?

### ISSUE THREAD

**Issue by CHCP** [xormplus/xorm#26]
Hi xormplus,
  Can I use xorm-redis-cache in xormplus,  there is no redis-cache code in xormplus.  Thanks.

**Comment by xormplus** [comment]
Hi @CHCP 

u can use  xorm-redis-cache in xormplus

**Comment by CHCP** [comment]
OK, Thanks

**Comment by CHCP** [comment]
Hi @xormplus 
  Another question, can I use xormplus for application local memory cache, like ehcache in Java? 

Thanks.
