### ISSUE TITLE
undefined: tablib.Exportable

### ISSUE THREAD

**Issue by sqeven** [xormplus/xorm#29]
![image](https://user-images.githubusercontent.com/18329103/54280390-5a2f2a80-45d2-11e9-87ac-1a8de6bd35f8.png)

**Comment by sqeven** [comment]
go dep vendor

**Comment by xormplus** [comment]
??? github.com/xormplus/xorm didn't use github.com/sqeven/go-tablib

**Comment by sqeven** [comment]
我解决了，是因为github.com/agrison/go-tablib有更新，而github.com/agrison/go-tablib发布的版本太旧了，go dep 默认拉最近发布版本，我fork一下，发布2.0.0就解决了
