### ISSUE TITLE
如何打印更详细的log？

### ISSUE THREAD

**Issue by piaohailin** [xormplus/xorm#3]
服务启动后打印sqlmap中的文件，可以断定xml文件以及加载
执行	err = x.SqlMapClient("select_demo", 1).Find(&demo)
demo数据中存在这个表
select_demo=	select id,name,mail,created,updated
		from demo 
        where id=?                          已经配置在文件中

打印结果

	log.Debug(demo)   []
	log.Error(err)       Error 1065: Query was empty

这个sql在数据库中可以执行的，为什么是无效sql？

**Comment by xormplus** [comment]
engine.ShowSQL(true)，会在控制台打印出执行的SQL语句；
你先看下具体执行的sql是什么？
另外engine.GetSql(key)可以看下这个key配置的sql是什么？
看你的错误，你执行的sql是空，这是mysql返回的错误。
问题应该还是在你的配置解析上
你的配置文件是什么样的？麻烦贴一下看看

**Comment by xormplus** [comment]
恩，你的问题是，需要先初始化xorm，然后在初始化sqlmap
