### ISSUE TITLE
sql错误没有写入日志

### ISSUE THREAD

**Issue by zhoulin1359** [xormplus/xorm#32]
日志配置：
                f, _ := os.Create("logs/sql.log")
		//log.CreateLog("sql").Writer()
		engine.ShowSQL(true)
		engine.ShowExecTime(true)
		_ = core.LogLevel(logC.Level)
		engine.Logger().SetLevel(core.LOG_INFO)
		engine.SetLogger(xorm.NewSimpleLogger(f))

Insert 返回出错，但没有记录日志
               Error 1406: Data too long for column 'name' at row 1

**Comment by xormplus** [comment]
感谢提交bug，已修复

**Comment by zhoulin1359** [comment]
thank
