### ISSUE TITLE
an error occur while using subQuery 

### ISSUE THREAD

**Issue by johntaiii** [xormplus/xorm#34]
> sql: converting argument $1 type: unsupported type xorm.sqlExpr, a struct

this is my code:

```
var actList []YActivityModel

err = Engine.Table("y_activity_model").Select("id,title,address").Where("id in (?)", Engine.Table("y_apply_model").Select("activityId").Where("uid = ? and like = 1", uid).QueryExpr()).Find(&actList)
```

did i miss something?

**Comment by xormplus** [comment]
Can you provide SQL logs?

**Comment by xormplus** [comment]
sorry,delete this feature in an update, and now it's restored

**Comment by xormplus** [comment]
pls update new version

**Comment by johntaiii** [comment]
seems caused another error :

`Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'like = 1))) AND (`deleted_at` IS NULL OR `deleted_at`=?)' at line 1`

following is sql log:

![nn](http://snappyimages.nextwavesrl.netdna-cdn.com/img/95cfc8e062d9e92f28f16073f3bd743b.png)

**Comment by johntaiii** [comment]
my code
`Engine.Table("ycy_activity_model").Select("id,title,adddress,locationDesc,applyStartTime,applyEndTime,activityStartTime,activityEndTime").Where("id in (?)", Engine.Table("ycy_apply_model").Select("activityId").Where("uid = ? AND like = 1",uid).QueryExpr()).Find(&actList)`

**Comment by johntaiii** [comment]
sorry, my mistake, it works now! thanks for your fantastic job!
