### ISSUE TITLE
编辑markdown格式文件，代码tag问题。

### ISSUE THREAD

**Issue by CHCP** [xormplus/xorm#36]
编辑markdown格式文件，代码tag```保存后变成了"""，导致数据库保存出错；而?则变成了$1，与要求不相符，该怎么解决这个问题？见图：
第一行是生成SQL语句，未执行，第二行是执行的SQL语句，发现上述两个符号变掉了。

![image](https://user-images.githubusercontent.com/5645296/59005607-a6040f80-8861-11e9-97e0-51c3b41f2fe9.png)

**Comment by CHCP** [comment]
补充下，INSERT语句是可以保存```和?的，但UPDATE语句不可以。见图：
![image](https://user-images.githubusercontent.com/5645296/59006274-5ecb4e00-8864-11e9-8059-83e30b5125bc.png)

**Comment by xormplus** [comment]
markdown文件格式？？？请贴你的源代码，感觉是你用法有问题

**Comment by CHCP** [comment]
谢谢回复。
1，golang执行数据库修改操作代码Exec如下：
`
func ExecuteSQL(sqlstr string) (int, error) {

	if ret, err := DB().Exec(sqlstr); nil == err {
		if rows, _ := ret.RowsAffected(); rows > 0 {
			return (int)(rows), nil
		} else {
			return 0, errors.New(datatype.ErrorNotFound.Message)
		}
	} else {
		//数据库或SQL错误记录日志，级别为Error。
		DB().Logger().Errorf(err.Error() + config.ToolmakerErrorLogTag)
		return 0, errors.New(datatype.ErrorDatabase.Message)
	}
}
`

参数sqlstr传入的是：
`
UPDATE task SET updated_at = '2019-06-06 23:56:43', name = 'test123', kind = 'Task', importance = 2, emergency = 2, priority = 2, processor_id = 10004, processor = 'gordon', data = data || '{"content":"代码段开始：\n```\nvar str string\n```\n\nHelp?Help123"}' WHERE product_id = 10001 AND id = 10095
`

但Exec执行的代码就变成了：
`
UPDATE task SET updated_at = '2019-06-06 23:56:43', name = 'test123', kind = 'Task', importance = 2, emergency = 2, priority = 2, processor_id = 10004, processor = 'gordon', data = data || '{"content":"代码段开始：\n"""\nvar str string\n"""\n\nHelp$1Help123"}' WHERE product_id = 10001 AND id = 10095
` 

2，创建记录使用的InsertOne函数如下，这个可以执行插入操作。
`
func (d *TaskDao) Create(session *xorm.Session, tsk *model.Task) (err error) {

	if nil == session {
		if _, err = sql.DB().InsertOne(tsk); nil != err {
			sql.DB().Logger().Errorf(err.Error() + config.ToolmakerErrorLogTag)
		}
		return err
	} 
`

**Comment by xormplus** [comment]
请问你使用的数据库是什么数据库？
```
ret, err := engine.Exec("update user set name= name || '{\"content\":\"代码段开始：\\n```\\nvar str string\\n```\\n\\nHelp?Help123\"}' where name='myname1'")
```
实际执行的sql
```
[xorm] [info]  2019/06/07 10:08:45.787591 [SQL][0xc000170900] update user set name= name || '{"content":"代码段开始：\n```\nvar str string\n```\n\nHelp?Help123"}' where name='myname1'
```
我测试，数据库中的数据也更新了。你看下你sql中的转义字符是否出现问题

**Comment by CHCP** [comment]
用的是postgresql 9.6数据库，使用了JSONB格式的NOSQL保存。

是转义字符的问题，插入记录时可以正确对”\等增加转义字符，修改时使用了PG的JSONB语法，导致没有增加转义字符\，但不知道如何在这种情况下增加转义字符处理，你有好的建议吗?

`
	// Update JSONB data

	if tsk.Data != nil {
		sqlstr += ", data = data || '" + string(tsk.Data[:]) + "'"
	}

`

**Comment by xormplus** [comment]
你的转移字符有问题，你对比你正确运行的insert语句
```
'{\"content\":\"代码段开始：\\n```\\nvar str string\\n```\\n\\nHelp?Help123\"}'
```
你错误运行的sql语句
```
'{"content":"代码段开始：\n"""\nvar str string\n"""\n\nHelp$1Help123"}'
```

**Comment by CHCP** [comment]
问题是，只要没有代码tag```，普通的markdown格式是可以Update成功的，如下代码段1是传入的SQL，代码段2是执行Update后的结果，没有转义字符也成功了。
还有个问题，字符?执行后变成了$1，这个与转义无关，是什么问题造成的呢？

代码段1
```
[xorm] [debug] 2019/06/08 18:27:30.283258 UPDATE task SET updated_at = '2019-06-08 08:27:30', name = '请求', kind = 'Task', importance = 2, emergency = 2, priority = 2, processor_id = 10004, processor = 'gordon', data = data || '{"content":"![logo.jpg](10082)\n\n# 阿斯蒂芬\n\n\n++阿萨大??++"}' WHERE product_id = 10001 AND id = 10100
```

代码段2
```
[xorm] [info]  2019/06/08 18:27:30.283258 [SQL][0xc0423bcc00] UPDATE task SET updated_at = '2019-06-08 08:27:30', name = '请求', kind = 'Task', importance = 2, emergency = 2, priority = 2, processor_id = 10004, processor = 'gordon', data = data || '{"content":"![logo.jpg](10082)\n\n# 阿斯蒂芬\n\n\n++阿萨大$1$2++"}' WHERE product_id = 10001 AND id = 10100
```

**Comment by CHCP** [comment]
我使用ORM的Update函数代替自己写的SQL语句解决了，多谢。

**Comment by xormplus** [comment]
本来orm的update函数就会帮你转义，你自己手写的就需要你自己转义

**Comment by CHCP** [comment]
是的，只能用ORM函数。
