### ISSUE TITLE
缓存没有生效

### ISSUE THREAD

**Issue by CHCP** [xormplus/xorm#38]
按照文档设置了缓存，手工修改数据库记录，发现查询出来的结果也修改了，并没有使用到缓存，麻烦请看下该如何解决，谢谢。
数据库是PostgreSQL9.6, 使用xormplus。

缓存设置如下：
```
		// set cache
		cacher := xorm.NewLRUCacher(xorm.NewMemoryStore(), 1000)
		engine.SetDefaultCacher(cacher)
		//engine.MapCacher(new(model.Dictionary), cacher)
		var dic model.Dictionary
		engine.MapCacher(&dic, cacher)

```
缓存使用如下：
```
func (d *DictionaryDao) GetList(listPara dto.DictionaryListPara) (datatype.DataListResp, error) {
	var list datatype.DataListResp
	dic := make([]model.Dictionary, 0)
	//var dic []model.Dictionary

	sql.DB().Find(&dic)
	list.List = dic
	list.Total = 0

	return list, nil
}

```

**Comment by xormplus** [comment]
你的叙述有我了解的地方，你手工修改数据库记录是以什么方式修改的？

**Comment by CHCP** [comment]
@xormplus 你好。
我增加缓存处理后，先查询一次数据库，得到结果是dictionary.name='安全'，然后通过Navicat工具直接修改数据库记录为’安全abc‘,再次查询，结果得到’安全abc‘。因为有了缓存，理论上应该得到’安全‘，而不是’安全abc‘，所以我觉得是缓存没有起到作用。

**Comment by xormplus** [comment]
请问这个表有主键么？没有主键的表中的数据将不会被缓存

**Comment by CHCP** [comment]
有个id自增主键。
![image](https://user-images.githubusercontent.com/5645296/59244141-84869780-8c56-11e9-92bc-81cbd557fb46.png)

**Comment by xormplus** [comment]
能否把数据库建表脚本和struct的代码发出来看看？

**Comment by CHCP** [comment]
结构如下，很小的一个数据表：
--Schema table sql statement;

DROP TABLE library.dictionary CASCADE;
CREATE TABLE library.dictionary (
    id BIGSERIAL PRIMARY KEY NOT NULL,
	product_id BIGINT,
	oid INTEGER,
	key VARCHAR(50) NOT NULL,
	value VARCHAR(100) NOT NULL,
	zhvalue VARCHAR(100),
	status INTEGER DEFAULT 1 NOT NULL,
	parent_id BIGINT, 
	intro VARCHAR(1000)	
);
COMMENT ON TABLE library.dictionary IS 'The dictionary table';
COMMENT ON COLUMN library.dictionary.id IS 'The primary key';
...

INSERT INTO library.dictionary (product_id,oid,key, value, zhvalue, status, parent_id, intro) VALUES (NULL,1,'main-feature', 'Capability', '核心能力', 1, NULL, 'Capability type of features');
...

**Comment by xormplus** [comment]
golang的结构图定义的代码看下？

**Comment by CHCP** [comment]
结构定义：

package model

// Don't use govalidator but valid.
type Dictionary struct {
	Id        uint64 `xorm:"'id' autoincr" json:"id,omitempty" valid:"optional"`
	ProductId uint64 `xorm:"'product_id'" json:"productId,omitempty" valid:"optional"`
	Oid       int    `xorm:"'oid'" json:"oid,omitempty" valid:"optional"`
	Key       string `xorm:"'key'" json:"key,omitempty" valid:"required,length(1|50)"`
	Value     string `xorm:"'value'" json:"value,omitempty" valid:"optional,length(1|100)"`
	Zhvalue   string `xorm:"'zhvalue'" json:"zhvalue,omitempty" valid:"optional,length(1|100)"`
	Status    int    `xorm:"'status'" json:"status,omitempty" valid:"optional,rang(1|2)"` //状态：1: Available, 2: Unavailable
	ParentId  uint64 `xorm:"'parent_id'" json:"parentId,omitempty" valid:"optional"`
	Intro     string `xorm:"'intro'" json:"intro,omitempty"  valid:"optional,length(1|1000)"`
}

// define table name:dictionary
func (d *Dictionary) TableName() string {
	return "dictionary"
}

**Comment by xormplus** [comment]
你这个结构体中没有定义主键，所以xorm无法识别，不会cache的

**Comment by CHCP** [comment]
奥，是的，我以为只要SQL语句设置了主键就可以了，原来结构体也需要设置。已经解决，多谢多谢。
