### ISSUE TITLE
主从配置NewSession问题

### ISSUE THREAD

**Issue by kiddlovemoon** [xormplus/xorm#39]
Engine 的 NewSession() 方法应增加对engineGroup的判断，如果为engineGroup 则sessionType为groupSession，否则主从配置无效。

**Comment by xormplus** [comment]
请详细描述一下，你这里指的主从配置无效是具体指什么？

**Comment by kiddlovemoon** [comment]
当时用SqlTemplateClient时，配置主从库是不生效的，所有查询也是走的主库。

**Comment by kiddlovemoon** [comment]
修改如下：
// NewSession New a session
func (engine *Engine) NewSession() *Session {
	session := &Session{engine: engine}
	session.Init()
	if engine.engineGroup != nil {
		session.sessionType = groupSession
	}
	return session
}

**Comment by xormplus** [comment]
你用Engine对象创建的session和EngineGroup对象创建的session本身就不一样啊。你要使用主从方式，就需要使用EngineGroup来创建session
