### ISSUE TITLE
关于分页问题

### ISSUE THREAD

**Issue by piaohailin** [xormplus/xorm#4]
数据分页例子
 x.Limit(10, 0).SqlMapClient("demo_byid", 1).Find(&demo)  

打印语句
 select id,name,mail,created,updated
                from demo
        where id=?
     LIMIT 10 [args] [1]

文档中没有类似x.Limit(10, 0).SqlMapClient("xxx", 1).的查询方法，是不是文档没有更新？
这种方式查询到底实现没有？

**Comment by xormplus** [comment]
《xorm操作指南》中有一个章节是介绍数据库分页查询

详见：[http://www.kancloud.cn/xormplus/xorm/250337](http://www.kancloud.cn/xormplus/xorm/250337)
