### ISSUE TITLE
参数化sql语法问题

### ISSUE THREAD

**Issue by piaohailin** [xormplus/xorm#5]
<sql id="demo_param">
		select id,name,mail,created,updated
		from demo 
        where id=?id and name=?name
	</sql>
paramMap := map[string]interface{}{"id": 2, "name": "bbbb"}
map中key对应？后面的字符串，运行OK

这个sql好丑，直接用通配符“？”的方式不行吗？即：where id=? and name=?
paramMap := map[string]interface{}{"id": 2, "name": "bbbb"}  匹配 where后面 id、name 这样的语法更好看。。

**Comment by xormplus** [comment]
如果使用map[string]interface{}类型作为sql参数，需要在sql语句中对map的每一个key绑定。
如果想直接使用用通配符“？”的方式，可以如下配置
~~~xml
<sql id="demo_param">
	select id,name,mail,created,updated
	from demo 
    where id=? and name=?
</sql>
~~~

go代码可以直接传参
~~~go
Engine.SqlMapClient("demo_param",2,"bbbb")
~~~

**Comment by piaohailin** [comment]
这种模式我用过没有问题。
还是觉得map方式更好一些。
