### ISSUE TITLE
请问oracle 使用orm 查询 格式错误怎么修复？

### ISSUE THREAD

**Issue by ogsyoo** [xormplus/xorm#51]
![image](https://user-images.githubusercontent.com/30709876/67265001-33799080-f4df-11e9-9074-efb061d05402.png)
![image](https://user-images.githubusercontent.com/30709876/67265010-3b393500-f4df-11e9-9130-7814bc2b1b7a.png)

**Comment by xormplus** [comment]
请更新最新版本
