### ISSUE TITLE
mod 引用问题

### ISSUE THREAD

**Issue by 2637309949** [xormplus/xorm#54]
能把dialect_mssql_test.go里的github.com/go-xorm/core替换成xorm.io/core吗, mod一直报错

**Comment by lx32056127** [comment]
+1 我也是这样报错.

**Comment by lx32056127** [comment]
> 能把dialect_mssql_test.go里的github.com/go-xorm/core替换成xorm.io/core吗, mod一直报错

shell下运行```go mod edit -replace=github.com/go-xorm/core@v0.6.3=xorm.io/core@v0.7.2``` 或在go.mod文件内添加一行
```
replace github.com/go-xorm/core v0.6.3 => xorm.io/core v0.7.2
```

**Comment by 2637309949** [comment]
> > 能把dialect_mssql_test.go里的github.com/go-xorm/core替换成xorm.io/core吗, mod一直报错
> 
> shell下运行`go mod edit -replace=github.com/go-xorm/core@v0.6.3=xorm.io/core@v0.7.2` 或在go.mod文件内添加一行
> 
> ```
> replace github.com/go-xorm/core v0.6.3 => xorm.io/core v0.7.2
> ```

可以在代码替换掉吗, 我的项目i引用了xorm, 别人引用了我的库(我的已经replace了), 都要别人的mod文件也要replace一次

**Comment by lx32056127** [comment]
> > > 能把dialect_mssql_test.go里的github.com/go-xorm/core替换成xorm.io/core吗, mod一直报错
> > 
> > 
> > shell下运行`go mod edit -replace=github.com/go-xorm/core@v0.6.3=xorm.io/core@v0.7.2` 或在go.mod文件内添加一行
> > ```
> > replace github.com/go-xorm/core v0.6.3 => xorm.io/core v0.7.2
> > ```
> 
> 可以在代码替换掉吗, 我的项目i引用了xorm, 别人引用了我的库(我的已经replace了), 都要别人的mod文件也要replace一次

那就得作者改或者自己fork一份改了

**Comment by xormplus** [comment]
请更新最新版本
