### ISSUE TITLE
module declares its path as: xorm.io/core

### ISSUE THREAD

**Issue by yunlongw** [xormplus/xorm#56]
```
        github.com/go-xorm/core: github.com/go-xorm/core@v0.6.3: parsing go.mod:
        module declares its path as: xorm.io/core
                but was required as: github.com/go-xorm/core
```
请问这个问题如何解决?

**Comment by xormplus** [comment]
请更新最新版本

**Comment by yashinnhl** [comment]
Any answers for this?

**Comment by zhangyasong123** [comment]
@yunlongw I have also encountered this problem, and I would like to know how to solve it. Can you answer that?评

**Comment by zhangyasong123** [comment]
ok.I found the answer. Please look at this image.
![image](https://user-images.githubusercontent.com/51359868/115493526-7d8b3000-a296-11eb-9065-603a616b408f.png)
