### ISSUE TITLE
Why did't I query data from MySQL,  please , help me!!

### ISSUE THREAD

**Issue by shiminyang** [xormplus/xorm#6]
I just want to get the project name and i send the SQL via XORM  and nothing is returned..
I verified the SQL statement in workbench of MySQL and it is worked...!!
My code segment are as follow, please help me to check where is problem..!
Thanks a lot...!!
....
type Project struct {
	Id int64 `json:"id"`

	**Name      string    `json:"name"`**
	ManagerId int64     `json:"managerId"`
	Url       string    `json:"url"`
	Comment   string    `json:"comment"`
	StartTime time.Time `json:"startTime"`

	CreatorId  int64     `json:"creatorId"`
	UpdatorId  int64     `json:"updatorId"`
	CreateTime time.Time `json:"createTime"`
	UpdateTime time.Time `json:"updateTime"`

	Manager *UserProfileDTO `json:"manager,omitempty" xorm:"-"`
	Creator *UserProfileDTO `json:"creator,omitempty" xorm:"-"`
	Updator *UserProfileDTO `json:"updator,omitempty" xorm:"-"`
}

type GetProjectByDeviceIdQuery struct {
	DeviceId int64 `json:"deviceId"`

	**Result []*Project `json:"-"`**
}

func GetProjectByDeviceId(query *m.**GetProjectByDeviceIdQuery**) error {
	**sql := `SELECT * FROM project WHERE id IN (SELECT device_assign.project_id FROM device_assign WHERE device_assign.device_id=?)`**
	query.Result = make([]*m.**Project**, 0)
	err := x.Sql(sql, query.DeviceId).Find(&query.Result)
	return err
}

**Comment by xormplus** [comment]
may u try it

···
sql := "SELECT * FROM project WHERE id IN (SELECT device_assign.project_id FROM device_assign WHERE device_assign.device_id=?)"
	result := make([]m.Project, 0)
	err := x.Sql(sql, query.DeviceId).Find(&result)
	query.Result = result
	return err
···

**Comment by shiminyang** [comment]
I have tried it and it was fine..  thanks a lot...
