### ISSUE TITLE
确实如此，在版本v0.0.0-20190926190243-42377f593eb1中也是如此，dialect_postgres.go在处理postgres中的tag【index】时报错“pq: syntax error at or near "."”。查询postgresql的官方文档http://www.postgres.cn/docs/9.3/sql-createindex.html，在create index name on table_name ( col...)语法中，name位置不能用“schema”."index_name"的模式，相反table_name可以使用"schema"."table_name"的模式。目前版本中的实现，刚好与实际情况相反，name使用了模式路径，tablename没有使用模式路径，所以报出“pq: syntax error at or near "."”

### ISSUE THREAD

**Issue by chenjitong** [xormplus/xorm#62]
确实如此，在版本v0.0.0-20190926190243-42377f593eb1中也是如此，dialect_postgres.go在处理postgres中的tag【index】时报错“pq: syntax error at or near "."”。查询postgresql的官方文档http://www.postgres.cn/docs/9.3/sql-createindex.html，在create index name on table_name ( col...)语法中，name位置不能用“schema”."index_name"的模式，相反table_name可以使用"schema"."table_name"的模式。目前版本中的实现，刚好与实际情况相反，name使用了模式路径，tablename没有使用模式路径，所以报出“pq: syntax error at or near "."”

_Originally posted by @chenjitong in https://github.com/xormplus/xorm/issues/40#issuecomment-594355629_

**Comment by xormplus** [comment]
@chenjitong 请更新最新版本

**Comment by chenjitong** [comment]
@xormplus 感谢回复，最新版本已经解决问题:)
