### ISSUE TITLE
go mod tidy下载报错

### ISSUE THREAD

**Issue by Felyne** [xormplus/xorm#68]
github.com/xormplus/xorm imports
github.com/xormplus/xorm/tags tested by
github.com/xormplus/xorm/tags.test imports
github.com/xormplus/dialects: git ls-remote -q https://github.com/xormplus/dialects in /home/chen/work/gopath/pkg/mod/cache/vcs/6ed4165c11b1cbfeffc2e639c983966f55199b7c2473d93bb346596c8eb3e7dc: exit status 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
github.com/xormplus/xorm imports
github.com/xormplus/xorm/tags tested by
github.com/xormplus/xorm/tags.test imports
github.com/xormplus/names: git ls-remote -q https://github.com/xormplus/names in /home/chen/work/gopath/pkg/mod/cache/vcs/80144a96dbbbf85ef96ca0692b316f8af5dea18be4cb482319753567a4815be7: exit status 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.

**Comment by WentaoJin** [comment]
请问这个有解决吗？我也遇到同样问题

**Comment by Felyne** [comment]
没有



---原始邮件---
发件人: "wentaojin"<notifications@github.com&gt;
发送时间: 2020年5月12日(周二) 上午10:22
收件人: "xormplus/xorm"<xorm@noreply.github.com&gt;;
抄送: "Felyne"<chenwd_135@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xormplus/xorm] go mod tidy下载报错 (#68)




 
请问这个有解决吗？我也遇到同样问题

**Comment by fzkun** [comment]
遇到同样问题

**Comment by fzkun** [comment]
@Felyne github.com/xormplus/tags/parser_test.go 里面的代码写错了，注释掉就可以拉下来

**Comment by Felyne** [comment]
我知道，问题是让作者注释啊

**Comment by xormplus** [comment]
@Felyne @fzkun 两位抱歉，最近才发现网易邮箱有问题，一直没收到任何邮件，现在才看到，已修复
