### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by enorzw** [xormplus/xorm#9]
../github.com/xormplus/xorm/sqltemplate_jet.go:55: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument to jet.NewSet
../github.com/xormplus/xorm/sqltemplate_jet.go:65: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument to jet.NewSet
../github.com/xormplus/xorm/sqltemplate_jet.go:189: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument tojet.NewSet
../github.com/xormplus/xorm/sqltemplate_jet.go:204: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument tojet.NewSet
../github.com/xormplus/xorm/sqltemplate_jet.go:224: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument tojet.NewSet
../github.com/xormplus/xorm/sqltemplate_jet.go:242: cannot use sqlTemplate.SqlTemplateRootDir (type string) as type jet.SafeWriter in argument tojet.NewSet

**Comment by xormplus** [comment]
thank u report this issue
i upgraded Jet template engine api to new version and updated govender
pls go get again
